cc_library(
    name = "lutdomain",
    srcs = ["lutdomain.cc"],
    hdrs = ["lutdomain.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "lutdomain_test",
    srcs = ["lutdomain_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
