cc_library(
    name = "lututil",
    srcs = [
        "lututil.cc",
    ],
    hdrs = [
        "lututil.h",
    ],
    deps = [
        "//lutmask:lutmask"
    ],
    visibility = ["//visibility:public"],
)

